version: '3.4'

services:
  db:
    image: couchbase:latest
    volumes:
      - ./couchbase/persist:/opt/couchbase/var
    ports:
      - "8091-8094:8091-8094"
      - "11210:11210"
    restart: always
    networks:
      poc-network:
        aliases:
          - db
  gateway:
    image: couchbase/sync-gateway:2.1.0-enterprise
    volumes: 
      - ./sync-gateway/config:/etc/sync_gateway/
      - ./sync-gateway/data:/opt/couchbase-sync-gateway/data 
    restart: always
    ports:
      - "4984-4985:4984-4985"
    networks:
      poc-network:
        aliases:
          - gateway
networks:
  poc-network:
